language: php

env:
  - SYMFONY_ENV=prod

install:
  - sudo apt-get install -y lftp

before_script:
  - composer --prefer-dist --no-dev --no-interaction --optimize-autoloader install

script: true

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
