language: php

install:
  - sudo apt-get install -y lftp

before_script:
  - composer --prefer-dist --dev --no-interaction install

script: true

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
